---
- name: installing cleanup scripts...
  become: yes
  become_user: root
  with_items: '{{docker_cleanup_scripts}}'
  copy: >
    src={{item}}
    dest={{docker_cleanup_install_dir}}/{{item}}
    mode=0755

- name: install systemd timer/services...
  become: yes
  become_user: root
  register: docker_cleanup_modified
  with_items:
    - docker-cleanup.timer
    - docker-cleanup.service
  template: >-
    src=usr/lib/systemd/system/{{item}}.j2
    dest=/usr/lib/systemd/system/{{item}}
    mode=0644

- name: systemctl daemon-reload
  become: yes
  become_user: root
  when: docker_cleanup_modified|changed
  command: systemctl daemon-reload

- name: launch timer
  become: yes
  become_user: root
  service: name=docker-cleanup.timer enabled=true state=started
