---
- name: installing cleanup scripts...
  become: yes
  become_user: root
  with_items: '{{ docker_cleanup_scripts }}'
  when: item.enabled
  template:
    src: '{{ item.script }}.j2'
    dest: '{{ item.d | default(docker_cleanup_install_dir) }}/{{ item.script }}'
    mode: 0755

- name: install systemd timer/services...
  become: yes
  become_user: root
  register: docker_cleanup_modified
  with_items:
    - docker-cleanup.timer
    - docker-cleanup.service
  template:
    src: '{{ item }}.j2'
    dest: /etc/systemd/system/{{ item }}
    mode: 0644

- name: systemctl daemon-reload
  become: yes
  become_user: root
  when: docker_cleanup_activate and docker_cleanup_modified|changed
  systemd:
    daemon_reload: yes

- name: launch timer
  become: yes
  become_user: root
  when: docker_cleanup_activate
  service:
    name: docker-cleanup.timer
    enabled: true
    state: started
