---
- name: installing {{item}}
  with_items: '{{docker_cleanup_scripts}}'
  copy: >
    src={{item}}
    dest={{docker_cleanup_install_dir}}/{{item}}
    owner=root
    group=root
    mode=0755

- name: install systemd timer/service
  register: docker_cleanup_modified
  with_items:
    - docker-cleanup.timer
    - docker-cleanup.service
  template: >-
    src=usr/lib/systemd/system/{{item}}.j2
    dest=/usr/lib/systemd/system/{{item}}
    owner=root
    group=root
    mode=0644

- name: systemctl daemon-reload
  when: docker_cleanup_modified
  command: systemctl daemon-reload

- name: launch timer
  service: name=docker-cleanup.timer enabled=true state=started
